// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADFVEegTBSVDS8GwyCWPw16_P5exCYkX4',
    appId: '1:185499435792:web:3b6fbc1a8448ed99175b95',
    messagingSenderId: '185499435792',
    projectId: 'lazycat-6910c',
    authDomain: 'lazycat-6910c.firebaseapp.com',
    storageBucket: 'lazycat-6910c.firebasestorage.app',
    measurementId: 'G-1B8TPMKEDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDETj4o80vRx9Ul7oinm-6qZdqr0gANtj8',
    appId: '1:185499435792:android:4fa127584d53d27b175b95',
    messagingSenderId: '185499435792',
    projectId: 'lazycat-6910c',
    storageBucket: 'lazycat-6910c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCplepKXpxev44L1GOnMawrpsB5SfVrjEw',
    appId: '1:185499435792:ios:775b21c6ccd3d6a6175b95',
    messagingSenderId: '185499435792',
    projectId: 'lazycat-6910c',
    storageBucket: 'lazycat-6910c.firebasestorage.app',
    iosBundleId: 'com.chandu.lazycat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCplepKXpxev44L1GOnMawrpsB5SfVrjEw',
    appId: '1:185499435792:ios:775b21c6ccd3d6a6175b95',
    messagingSenderId: '185499435792',
    projectId: 'lazycat-6910c',
    storageBucket: 'lazycat-6910c.firebasestorage.app',
    iosBundleId: 'com.chandu.lazycat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADFVEegTBSVDS8GwyCWPw16_P5exCYkX4',
    appId: '1:185499435792:web:15353f0d01bb0433175b95',
    messagingSenderId: '185499435792',
    projectId: 'lazycat-6910c',
    authDomain: 'lazycat-6910c.firebaseapp.com',
    storageBucket: 'lazycat-6910c.firebasestorage.app',
    measurementId: 'G-ZZ1HXQD1QR',
  );

}